# Use OpenJDK 21 as the base Docker image
image: openjdk:21-slim

# Pipeline Stages
stages:
  - build
  - test
  - deploy

# Project Variables
variables:
  PROJECT_NAME: "Superchain"  
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle" 
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"  # Gradle options to optimize performance

# Cache Gradle wrapper and caches between jobs to speed up builds
cache:
  key: "$CI_JOB_NAME"
  paths:
    - .gradle/wrapper
    - .gradle/caches

# Before Jobs
before_script:
  - export GRADLE_USER_HOME=$CI_PROJECT_DIR/.gradle 
  - chmod +x gradlew

# Build stage
build:
  stage: build
  script:
    - ./gradlew assemble

# Test Stage
test:
  stage: test 
  script:
    - ./gradlew test 

# Deploy Stage
deploy:
  stage: deploy  
  script:
    - echo "Deploying application..."
    # Todo [deployment script here]
    # template: scp build/libs/$PROJECT_NAME.jar user@server:/path/to/deploy/
  only:
    - master   # Only run this job on the 'master' branch
    - main      # Only run this job on the 'main' branch
