name: Publish package to GitHub Packages
run-name: ${{ github.actor }} 🚀🚀🚀
on:
  release:
    types: [created]
jobs:
  publish-to-github-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - run: echo "${{ github.event_name }} event."
      - uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner. Branch - ${{ github.ref }}"
        if: success()

      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4

      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.PUB_TOKEN }}
